services:
  hazmat-rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hazmat-assistant
    ports:
      - "8501:8501"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    mem_limit: 1g
    cpus: "2"
    networks:
      - hazmat-network

networks:
  hazmat-network:
    driver: bridge
